### ISSUE TITLE
Errors in Instagram links when hashtags have capital letters

### ISSUE THREAD

**Issue by lrkwll** [maxlath/hashtags-hub#11]
Suggest changing hashtags in Instagram links to all lowercase. Hashtags with capital letters can fail, especially with less active tags, but will work when in all lowercase. For example, https://www.instagram.com/explore/tags/SphereLasVegas shows an error page, but https://www.instagram.com/explore/tags/spherelasvegas works fine.

**Comment by maxlath** [comment]
Thanks for reporting! Done in  996bcf4
