### ISSUE TITLE
Peertube.social is about to go down

### ISSUE THREAD

**Issue by AutomCoding** [maxlath/hashtags-hub#4]
[Peertube.social](https://peertube.social/) will be shut down on November 9th. This means https://github.com/maxlath/hashtags-hub/blob/f0ddf8706241041813da240b63ffa2413459f41f/server/templates/hashtag.js#L99 needs changing. A good alternative in my opinion would be `https://sepiasearch.org/search?tagsOneOf=$1` as it would include all servers on [Framasoft's instance list](https://instances.joinpeertube.org/instances), but that does not work at the moment due to [this issue](https://framagit.org/framasoft/peertube/search-index/-/issues/28).

**Comment by maxlath** [comment]
sepiasearch issue was fixed, so it's now online! :tada:
